pagy:
  config:
    page:
      default: 10

faker:
  internet:
    email:
      domain_gmail: "gmail.com"
  number:
    digits_10: 10

devices:
  excel:
    one_office:
      pane:
        top_left_cell: "A2"
        state: "frozen"
        y_split: 1
        x_split: 0
        active_pane: "bottom_right"

spec:
  number_of_records_25: 25

skeleton:
  number_of_records_5: 5
  number_of_records_4: 4
  number_of_records_3: 3
